# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateButton.setGeometry(QtCore.QRect(510, 320, 61, 23))
        self.CreateButton.setObjectName("CreateButton")
        self.scrollAreaLeft = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaLeft.setGeometry(QtCore.QRect(30, 40, 251, 251))
        self.scrollAreaLeft.setWidgetResizable(True)
        self.scrollAreaLeft.setObjectName("scrollAreaLeft")
        self.scrollAreaWidgetContentsLeft = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsLeft.setGeometry(QtCore.QRect(0, 0, 249, 249))
        self.scrollAreaWidgetContentsLeft.setObjectName("scrollAreaWidgetContentsLeft")
        self.scrollAreaLeft.setWidget(self.scrollAreaWidgetContentsLeft)
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(30, 10, 61, 23))
        self.OpenButton.setObjectName("OpenButton")
        self.PathDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.PathDisplay.setGeometry(QtCore.QRect(110, 10, 461, 20))
        self.PathDisplay.setReadOnly(True)
        self.PathDisplay.setObjectName("PathDisplay")
        self.OutPathDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.OutPathDisplay.setGeometry(QtCore.QRect(100, 320, 401, 20))
        self.OutPathDisplay.setReadOnly(True)
        self.OutPathDisplay.setClearButtonEnabled(False)
        self.OutPathDisplay.setObjectName("OutPathDisplay")
        self.randomSeedBox = QtWidgets.QCheckBox(self.centralwidget)
        self.randomSeedBox.setGeometry(QtCore.QRect(470, 300, 101, 16))
        self.randomSeedBox.setObjectName("randomSeedBox")
        self.OutPathSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.OutPathSelectButton.setGeometry(QtCore.QRect(30, 320, 61, 23))
        self.OutPathSelectButton.setObjectName("OutPathSelectButton")
        self.scrollAreaRight = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaRight.setGeometry(QtCore.QRect(320, 40, 251, 251))
        self.scrollAreaRight.setWidgetResizable(True)
        self.scrollAreaRight.setObjectName("scrollAreaRight")
        self.scrollAreaWidgetContentsRight = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsRight.setGeometry(QtCore.QRect(0, 0, 249, 249))
        self.scrollAreaWidgetContentsRight.setObjectName("scrollAreaWidgetContentsRight")
        self.scrollAreaRight.setWidget(self.scrollAreaWidgetContentsRight)
        self.AllToRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllToRightButton.setGeometry(QtCore.QRect(290, 130, 21, 21))
        self.AllToRightButton.setObjectName("AllToRightButton")
        self.AllToLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllToLeftButton.setGeometry(QtCore.QRect(290, 170, 21, 21))
        self.AllToLeftButton.setObjectName("AllToLeftButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 300, 171, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Biome modifier for Terralith"))
        self.CreateButton.setText(_translate("MainWindow", "Create"))
        self.OpenButton.setText(_translate("MainWindow", "Open"))
        self.randomSeedBox.setText(_translate("MainWindow", "Randomize seed"))
        self.OutPathSelectButton.setText(_translate("MainWindow", "Browse..."))
        self.AllToRightButton.setText(_translate("MainWindow", "->"))
        self.AllToLeftButton.setText(_translate("MainWindow", "<-"))
        self.label.setText(_translate("MainWindow", "Datapack will be saved at:"))
