# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateButton.setGeometry(QtCore.QRect(480, 330, 61, 23))
        self.CreateButton.setObjectName("CreateButton")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(59, 39, 481, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.AllButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllButton.setGeometry(QtCore.QRect(60, 300, 71, 21))
        self.AllButton.setObjectName("AllButton")
        self.NoneButton = QtWidgets.QPushButton(self.centralwidget)
        self.NoneButton.setGeometry(QtCore.QRect(140, 300, 71, 21))
        self.NoneButton.setObjectName("NoneButton")
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(60, 10, 61, 23))
        self.OpenButton.setObjectName("OpenButton")
        self.PathDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.PathDisplay.setGeometry(QtCore.QRect(130, 10, 411, 20))
        self.PathDisplay.setReadOnly(True)
        self.PathDisplay.setObjectName("PathDisplay")
        self.OutPathDisplay = QtWidgets.QLineEdit(self.centralwidget)
        self.OutPathDisplay.setGeometry(QtCore.QRect(130, 330, 341, 20))
        self.OutPathDisplay.setReadOnly(True)
        self.OutPathDisplay.setClearButtonEnabled(False)
        self.OutPathDisplay.setObjectName("OutPathDisplay")
        self.randomSeedBox = QtWidgets.QCheckBox(self.centralwidget)
        self.randomSeedBox.setGeometry(QtCore.QRect(440, 300, 101, 17))
        self.randomSeedBox.setObjectName("randomSeedBox")
        self.OutPathSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.OutPathSelectButton.setGeometry(QtCore.QRect(60, 330, 61, 23))
        self.OutPathSelectButton.setObjectName("OutPathSelectButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Biome modifier for Terralith"))
        self.CreateButton.setText(_translate("MainWindow", "Create"))
        self.AllButton.setText(_translate("MainWindow", "Check All"))
        self.NoneButton.setText(_translate("MainWindow", "Uncheck All"))
        self.OpenButton.setText(_translate("MainWindow", "Open"))
        self.randomSeedBox.setText(_translate("MainWindow", "Randomize seed"))
        self.OutPathSelectButton.setText(_translate("MainWindow", "Browse..."))
